# Site settings
title: Appknox
email: hello@appknox.com
description: > # this means to ignore newlines until "baseurl:"
  Appknox - Mobile app vulnerability detection and security certification
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.appknox.com" # the base hostname & protocol for your site
twitter_username: appknox
github_username:  appknox

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
